# constants file for BBDN-REST_DEMO-Python

#IDs for create
DSKEXTERNALID = 'BBDN-PYTHON-REST-DEMO-DSK'
COURSEEXTERNALID = 'BBDN-PYTHON-REST-DEMO-COURSE'
TERMEXTERNALID = 'BBDN-PYTHON-REST-DEMO-TERM'
USEREXTERNALID = 'BBDN-PYTHON-REST-DEMO-USER'
